apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  selector:
    name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: iindex.docker.io/ajayvohra2005/hello-world:1.0.0
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: helloworldkey